create table if not exists public.heb_invoices (
  id bigint generated by default as identity primary key,
  month text not null default '',
  type text not null default 'HEB EDLC Allowances',
  check_number text not null default '',
  check_date date,
  check_amount numeric,
  invoice_number text not null default '',
  invoice_date date,
  gross_amount numeric,
  discount_amount numeric,
  adjustment_amount numeric,
  memo_code text not null default '',
  net_amount numeric,
  explanation text not null default '',
  source_file_name text not null default '',
  source_file_type text not null default '',
  line_number integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists heb_invoices_month_idx
  on public.heb_invoices (month);

create index if not exists heb_invoices_type_idx
  on public.heb_invoices (type);

create index if not exists heb_invoices_check_number_idx
  on public.heb_invoices (check_number);

create index if not exists heb_invoices_check_date_idx
  on public.heb_invoices (check_date);

create index if not exists heb_invoices_invoice_number_idx
  on public.heb_invoices (invoice_number);

create index if not exists heb_invoices_source_file_idx
  on public.heb_invoices (source_file_name);

alter table public.heb_invoices enable row level security;

drop policy if exists "Authenticated users can read HEB invoices" on public.heb_invoices;
create policy "Authenticated users can read HEB invoices"
  on public.heb_invoices
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can upload HEB invoices" on public.heb_invoices;
create policy "Authenticated users can upload HEB invoices"
  on public.heb_invoices
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update HEB invoices" on public.heb_invoices;
create policy "Authenticated users can update HEB invoices"
  on public.heb_invoices
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete HEB invoices" on public.heb_invoices;
create policy "Authenticated users can delete HEB invoices"
  on public.heb_invoices
  for delete
  to authenticated
  using (true);

alter table public.user_permissions
  add column if not exists can_view_database_heb_invoices boolean not null default false;

update public.user_permissions
set can_view_database_heb_invoices = true
where lower(email) = 'kevin@wondermonday.com';
