create table if not exists public.hyvee_invoices (
  id bigint generated by default as identity primary key,
  month text not null default '',
  type text not null default 'Hy-Vee EDLC Allowances',
  check_number text not null default '',
  check_date date,
  check_amount numeric,
  invoice_number text not null default '',
  invoice_date date,
  gross_amount numeric,
  discount_amount numeric,
  adjustment_amount numeric,
  memo_code text not null default '',
  net_amount numeric,
  explanation text not null default '',
  source_file_name text not null default '',
  source_file_type text not null default '',
  source_file_path text,
  line_number integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.hyvee_invoices
  add column if not exists source_file_path text;

create index if not exists hyvee_invoices_month_idx
  on public.hyvee_invoices (month);

create index if not exists hyvee_invoices_type_idx
  on public.hyvee_invoices (type);

create index if not exists hyvee_invoices_check_number_idx
  on public.hyvee_invoices (check_number);

create index if not exists hyvee_invoices_check_date_idx
  on public.hyvee_invoices (check_date);

create index if not exists hyvee_invoices_invoice_number_idx
  on public.hyvee_invoices (invoice_number);

create index if not exists hyvee_invoices_source_file_idx
  on public.hyvee_invoices (source_file_name);

alter table public.hyvee_invoices enable row level security;

drop policy if exists "Authenticated users can read Hy-Vee invoices" on public.hyvee_invoices;
create policy "Authenticated users can read Hy-Vee invoices"
  on public.hyvee_invoices
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can upload Hy-Vee invoices" on public.hyvee_invoices;
create policy "Authenticated users can upload Hy-Vee invoices"
  on public.hyvee_invoices
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update Hy-Vee invoices" on public.hyvee_invoices;
create policy "Authenticated users can update Hy-Vee invoices"
  on public.hyvee_invoices
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete Hy-Vee invoices" on public.hyvee_invoices;
create policy "Authenticated users can delete Hy-Vee invoices"
  on public.hyvee_invoices
  for delete
  to authenticated
  using (true);

do $$
begin
  if to_regclass('public.heb_invoices') is not null then
    insert into public.hyvee_invoices (
      month,
      type,
      check_number,
      check_date,
      check_amount,
      invoice_number,
      invoice_date,
      gross_amount,
      discount_amount,
      adjustment_amount,
      memo_code,
      net_amount,
      explanation,
      source_file_name,
      source_file_type,
      source_file_path,
      line_number,
      created_at
    )
    select
      old.month,
      case
        when nullif(old.type, '') is null then 'Hy-Vee EDLC Allowances'
        when old.type ~* '^HEB[[:space:]]+' then regexp_replace(old.type, '^HEB[[:space:]]+', 'Hy-Vee ', 'i')
        else old.type
      end,
      old.check_number,
      old.check_date,
      old.check_amount,
      old.invoice_number,
      old.invoice_date,
      old.gross_amount,
      old.discount_amount,
      old.adjustment_amount,
      old.memo_code,
      old.net_amount,
      old.explanation,
      old.source_file_name,
      old.source_file_type,
      null,
      old.line_number,
      old.created_at
    from public.heb_invoices old
    where not exists (
      select 1
      from public.hyvee_invoices existing
      where existing.source_file_name = old.source_file_name
        and existing.line_number = old.line_number
        and existing.invoice_number = old.invoice_number
        and existing.check_number = old.check_number
    );
  end if;
end $$;

alter table public.user_permissions
  add column if not exists can_view_database_hyvee_invoices boolean not null default false;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'user_permissions'
      and column_name = 'can_view_database_heb_invoices'
  ) then
    execute '
      update public.user_permissions
      set can_view_database_hyvee_invoices =
        coalesce(can_view_database_hyvee_invoices, false)
        or coalesce(can_view_database_heb_invoices, false)
    ';
  end if;
end $$;

update public.user_permissions
set can_view_database_hyvee_invoices = true
where lower(email) = 'kevin@wondermonday.com';
