create table if not exists public.tony_invoice_wires (
  id bigint generated by default as identity primary key,
  month text not null default '',
  wired_on date,
  ach_number text not null default '',
  total_wire numeric,
  source_file_name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.tony_invoice_details (
  id bigint generated by default as identity primary key,
  wire_id bigint not null references public.tony_invoice_wires(id) on delete cascade,
  invoice_number text not null default '',
  po_number text not null default '',
  invoice_amount numeric,
  discount_amount numeric,
  amount_paid numeric,
  comment text not null default '',
  type text not null default '',
  line_number integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tony_invoice_detail_type_splits (
  id bigint generated by default as identity primary key,
  detail_id bigint not null references public.tony_invoice_details(id) on delete cascade,
  type text not null default '',
  amount numeric,
  created_at timestamptz not null default now()
);

alter table public.tony_invoice_details
  add column if not exists type text not null default '';

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'tony_invoice_details'
      and column_name = 'comment'
  ) then
    update public.tony_invoice_details
    set type = comment
    where coalesce(type, '') = ''
      and coalesce(comment, '') <> '';
  end if;
end $$;

create index if not exists tony_invoice_wires_month_idx
  on public.tony_invoice_wires (month);

create index if not exists tony_invoice_wires_wired_on_idx
  on public.tony_invoice_wires (wired_on);

create index if not exists tony_invoice_wires_ach_number_idx
  on public.tony_invoice_wires (ach_number);

create index if not exists tony_invoice_details_wire_id_idx
  on public.tony_invoice_details (wire_id);

create index if not exists tony_invoice_details_invoice_number_idx
  on public.tony_invoice_details (invoice_number);

create index if not exists tony_invoice_details_type_idx
  on public.tony_invoice_details (type);

create index if not exists tony_invoice_detail_type_splits_detail_id_idx
  on public.tony_invoice_detail_type_splits (detail_id);

create index if not exists tony_invoice_detail_type_splits_type_idx
  on public.tony_invoice_detail_type_splits (type);

alter table public.tony_invoice_wires enable row level security;
alter table public.tony_invoice_details enable row level security;
alter table public.tony_invoice_detail_type_splits enable row level security;

drop policy if exists "Authenticated users can read Tony invoice wires" on public.tony_invoice_wires;
create policy "Authenticated users can read Tony invoice wires"
  on public.tony_invoice_wires
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can upload Tony invoice wires" on public.tony_invoice_wires;
create policy "Authenticated users can upload Tony invoice wires"
  on public.tony_invoice_wires
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update Tony invoice wires" on public.tony_invoice_wires;
create policy "Authenticated users can update Tony invoice wires"
  on public.tony_invoice_wires
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete Tony invoice wires" on public.tony_invoice_wires;
create policy "Authenticated users can delete Tony invoice wires"
  on public.tony_invoice_wires
  for delete
  to authenticated
  using (true);

drop policy if exists "Authenticated users can read Tony invoice details" on public.tony_invoice_details;
create policy "Authenticated users can read Tony invoice details"
  on public.tony_invoice_details
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can upload Tony invoice details" on public.tony_invoice_details;
create policy "Authenticated users can upload Tony invoice details"
  on public.tony_invoice_details
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update Tony invoice details" on public.tony_invoice_details;
create policy "Authenticated users can update Tony invoice details"
  on public.tony_invoice_details
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete Tony invoice details" on public.tony_invoice_details;
create policy "Authenticated users can delete Tony invoice details"
  on public.tony_invoice_details
  for delete
  to authenticated
  using (true);

drop policy if exists "Authenticated users can read Tony invoice type splits" on public.tony_invoice_detail_type_splits;
create policy "Authenticated users can read Tony invoice type splits"
  on public.tony_invoice_detail_type_splits
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can upload Tony invoice type splits" on public.tony_invoice_detail_type_splits;
create policy "Authenticated users can upload Tony invoice type splits"
  on public.tony_invoice_detail_type_splits
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update Tony invoice type splits" on public.tony_invoice_detail_type_splits;
create policy "Authenticated users can update Tony invoice type splits"
  on public.tony_invoice_detail_type_splits
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete Tony invoice type splits" on public.tony_invoice_detail_type_splits;
create policy "Authenticated users can delete Tony invoice type splits"
  on public.tony_invoice_detail_type_splits
  for delete
  to authenticated
  using (true);

alter table public.user_permissions
  add column if not exists can_view_database_tony_invoices boolean not null default false;

update public.user_permissions
set can_view_database_tony_invoices = true
where lower(email) = 'kevin@wondermonday.com';
