create table if not exists public.unfi_invoices (
  id bigint generated by default as identity primary key,
  month text not null,
  description text not null default '',
  upc text not null default '',
  sales_period_fob numeric,
  deal_oi_percent numeric,
  promo_cases_to_cover numeric,
  promo_dollars_to_cover numeric,
  total numeric,
  po_number text not null default '',
  po_received_date date,
  invoice_number text not null default '',
  source_file_name text not null default '',
  line_number integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists unfi_invoices_month_idx
  on public.unfi_invoices (month);

create index if not exists unfi_invoices_source_file_idx
  on public.unfi_invoices (source_file_name);

create index if not exists unfi_invoices_invoice_number_idx
  on public.unfi_invoices (invoice_number);

alter table public.unfi_invoices enable row level security;

drop policy if exists "Authenticated users can read UNFI invoices" on public.unfi_invoices;
create policy "Authenticated users can read UNFI invoices"
  on public.unfi_invoices
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can upload UNFI invoices" on public.unfi_invoices;
create policy "Authenticated users can upload UNFI invoices"
  on public.unfi_invoices
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update UNFI invoices" on public.unfi_invoices;
create policy "Authenticated users can update UNFI invoices"
  on public.unfi_invoices
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete UNFI invoices" on public.unfi_invoices;
create policy "Authenticated users can delete UNFI invoices"
  on public.unfi_invoices
  for delete
  to authenticated
  using (true);

alter table public.user_permissions
  add column if not exists can_view_database_unfi_invoices boolean not null default false;

update public.user_permissions
set can_view_database_unfi_invoices = true
where lower(email) = 'kevin@wondermonday.com';
