create table if not exists public.unfi_invoices (
  id bigint generated by default as identity primary key,
  month text not null,
  type text not null default '',
  check_date date,
  check_number text not null default '',
  invoice_date date,
  invoice_number text not null default '',
  description text not null default '',
  upc text not null default '',
  sales_period_fob numeric,
  deal_oi_percent numeric,
  promo_cases_to_cover numeric,
  promo_dollars_to_cover numeric,
  total numeric,
  gross_amount numeric,
  discount_amount numeric,
  net_amount numeric,
  po_number text not null default '',
  po_received_date date,
  source_file_name text not null default '',
  source_file_type text not null default '',
  attachment_file_name text,
  attachment_file_type text,
  attachment_file_path text,
  line_number integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.unfi_invoices
  add column if not exists type text not null default '',
  add column if not exists check_date date,
  add column if not exists check_number text not null default '',
  add column if not exists invoice_date date,
  add column if not exists gross_amount numeric,
  add column if not exists discount_amount numeric,
  add column if not exists net_amount numeric,
  add column if not exists source_file_type text not null default '',
  add column if not exists attachment_file_name text,
  add column if not exists attachment_file_type text,
  add column if not exists attachment_file_path text;

create index if not exists unfi_invoices_month_idx
  on public.unfi_invoices (month);

create index if not exists unfi_invoices_source_file_idx
  on public.unfi_invoices (source_file_name);

create index if not exists unfi_invoices_attachment_file_idx
  on public.unfi_invoices (attachment_file_path);

create index if not exists unfi_invoices_invoice_number_idx
  on public.unfi_invoices (invoice_number);

create index if not exists unfi_invoices_check_date_idx
  on public.unfi_invoices (check_date);

create index if not exists unfi_invoices_check_number_idx
  on public.unfi_invoices (check_number);

create index if not exists unfi_invoices_type_idx
  on public.unfi_invoices (type);

alter table public.unfi_invoices enable row level security;

drop policy if exists "Authenticated users can read UNFI invoices" on public.unfi_invoices;
create policy "Authenticated users can read UNFI invoices"
  on public.unfi_invoices
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can upload UNFI invoices" on public.unfi_invoices;
create policy "Authenticated users can upload UNFI invoices"
  on public.unfi_invoices
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update UNFI invoices" on public.unfi_invoices;
create policy "Authenticated users can update UNFI invoices"
  on public.unfi_invoices
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete UNFI invoices" on public.unfi_invoices;
create policy "Authenticated users can delete UNFI invoices"
  on public.unfi_invoices
  for delete
  to authenticated
  using (true);

alter table public.user_permissions
  add column if not exists can_view_database_unfi_invoices boolean not null default false;

update public.user_permissions
set can_view_database_unfi_invoices = true
where lower(email) = 'kevin@wondermonday.com';
