create table if not exists public.wegmans_invoices (
  id bigint generated by default as identity primary key,
  vendor text not null default 'Wegman',
  month text not null,
  run_date date,
  invoice text not null default '',
  description text not null default '',
  inv_number text not null default '',
  chargeback numeric,
  type text not null default 'Wegman''s Chargeback',
  source_file_name text not null default '',
  line_number integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists wegmans_invoices_month_idx
  on public.wegmans_invoices (month);

create index if not exists wegmans_invoices_run_date_idx
  on public.wegmans_invoices (run_date);

create index if not exists wegmans_invoices_invoice_idx
  on public.wegmans_invoices (invoice);

create index if not exists wegmans_invoices_source_file_idx
  on public.wegmans_invoices (source_file_name);

alter table public.wegmans_invoices enable row level security;

drop policy if exists "Authenticated users can read Wegmans invoices" on public.wegmans_invoices;
create policy "Authenticated users can read Wegmans invoices"
  on public.wegmans_invoices
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can upload Wegmans invoices" on public.wegmans_invoices;
create policy "Authenticated users can upload Wegmans invoices"
  on public.wegmans_invoices
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update Wegmans invoices" on public.wegmans_invoices;
create policy "Authenticated users can update Wegmans invoices"
  on public.wegmans_invoices
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete Wegmans invoices" on public.wegmans_invoices;
create policy "Authenticated users can delete Wegmans invoices"
  on public.wegmans_invoices
  for delete
  to authenticated
  using (true);

alter table public.user_permissions
  add column if not exists can_view_database_wegmans boolean not null default false;

update public.user_permissions
set can_view_database_wegmans = true
where lower(email) = 'kevin@wondermonday.com';
